# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/ubuntu/workspace/leoedkII
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/ubuntu/workspace/leoedkII/BaseTools
fi
if [ -e /home/ubuntu/workspace/leoedkII/BaseTools/Bin/Linux-x86_64 ]
then
  FOUND_TOOLS_PATH_BIN=0
  for DIR in $(echo $PATH | tr ':' ' '); do
    if [ "$DIR" = "/home/ubuntu/workspace/leoedkII/BaseTools/Bin/Linux-x86_64" ]; then
      FOUND_TOOLS_PATH_BIN=1
    fi
  done
  if [ $FOUND_TOOLS_PATH_BIN = 0 ]
  then
    export PATH=/home/ubuntu/workspace/leoedkII/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
